import localFont from "next/font/local";
import "./globals.css";
import Header from "../../components/body/header";
import Hero from "../../components/hero";
import Footer from "../../components/body/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className=" mx-auto justify-center">
          <div className="bg-[#004F44] text-white min-h-screen w-full">
            <Header />
            <Hero />
          </div>
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
